//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTruyenV6.Control_NguoiDung.TrangTruyen {
    
    
    public partial class UiThongTinTruyen {
    }
}
